### ISSUE TITLE
Why cant I see logs?

### ISSUE THREAD

**Issue by TimTruston** [ihenvyr/react-chrome-extension#2]
Good work here.

I am trying to get an idea of the flow of operations on this extension. So I added a bunch of console.logs throughout the js files on the root folder. 

When I right click on the popup and "Inspect Popup" I only see logs on entry.popup.js and actions.js. 

Would you know why the others are not logging or briefly explain the flow? 
Thanks!
![Screen Shot 2020-05-11 at 8 59 20 AM](https://user-images.githubusercontent.com/2056593/81528602-c1c34000-9365-11ea-8c74-1d312b05e413.png)

**Comment by ihenvyr** [comment]
Hi @MwirabuaTim,

Thanks for your interest in the project :)

> When I right click on the popup and "Inspect Popup" I only see logs on entry.popup.js and actions.js.

That is correct, to see other logs, you'll need to inspect other views. In the chrome extension details page, you can inspect the "background" and "options". Please see the following screenshot. You can inspect the "background page" and "Extension options" there.

![image](https://user-images.githubusercontent.com/2912201/81537677-269b8c00-93a0-11ea-8234-c220f75b5bf0.png)

As for "content" logs, you can simply view it in the devtools console when visiting a page.

> Would you know why the others are not logging or briefly explain the flow?

Content, Background, Options and Popup views are separately rendered on different parts of the page, that's the main reason I guess why we can't see other logs in one view.

**Comment by TimTruston** [comment]
Thanks! So far i have been able to inspect the popup, content script and background page. But not the options page since the option to inspect it is not accessible. You can confirm that. Thanks again!

**Comment by ihenvyr** [comment]
Hi, you can inspect the options through

![extension-options](https://user-images.githubusercontent.com/2912201/81548124-5f8f2d00-93af-11ea-8a46-30d293a342cd.gif)

**Comment by TimTruston** [comment]
I can see that now. Thanks.
