### ISSUE TITLE
Cannot use the string "option"

### ISSUE THREAD

**Issue by TimTruston** [ihenvyr/react-chrome-extension#3]
When I use a string with the word "option" the code fails to run.

This version with "optios" logs but wont work because the options page is "options.html"...

![Screen Shot 2020-05-30 at 7 46 10 PM](https://user-images.githubusercontent.com/2056593/83334597-4394f200-a2b0-11ea-9a02-24ec00086cf9.png)

This version with "options" does not log

![Screen Shot 2020-05-30 at 7 45 29 PM](https://user-images.githubusercontent.com/2056593/83334581-337d1280-a2b0-11ea-878a-131c8d702147.png)

**Comment by ihenvyr** [comment]
You'll need to check the chrome extension docs about it. For most users it's better to show a menu-like option component inside the Content instead of leading them to unfamiliar chrome extension options page :)

**Comment by TimTruston** [comment]
Sorry, i had disabled logging the word "option" on my chrome dev tools way back. 😪
![20200531_074339](https://user-images.githubusercontent.com/2056593/83344654-7ec80d00-a312-11ea-94e9-d12c2590b71e.jpg)
