### ISSUE TITLE
Running contentscript on webpack-dev-server

### ISSUE THREAD

**Issue by TimTruston** [ihenvyr/react-chrome-extension#4]
My current development process (using this toolkit) involves the following
1. Keep running "webpack --mode development --watch"
2. Make a change on the codebase
3. Wait for webpack to rebuild the new output
4. Go to chrome://extensions/ page
5. Pressing the refresh button on the extension
6. Refresh a live webpage to see the content script ui. (I have made it autoload after any web page loads for quick testing)

Just noticed how tiring and slow this whole process is...

So I did the following to try to run the contentscript on localhost:

1. Installed "webpack-dev-server" 

2. Added the configuration below on webpack.config.js
```

devServer: {
    contentBase: path.join(__dirname, 'build'),
    port: 9999,
    writeToDisk: true
  }

```
3. Ran 'webpack-dev-server' on my console
4. Go to http://localhost:9999
5. Clicked on content.html

Too bad - the content script ui didnt load... no errors on my console either...
What could I be doing wrong?

**Comment by TimTruston** [comment]
I suspect this is an issue with webext-redux itself. I have openned a related issue here https://github.com/tshaddix/webext-redux/issues/249

**Comment by ihenvyr** [comment]
That would be a great idea. However you can't simply use the `webpack-dev-server` theoretically because the scripts has global variables that must invoke inside chrome extension, like chrome.storage etc.

**Comment by TimTruston** [comment]
> That would be a great idea. However you can't simply use the `webpack-dev-server` theoretically because the scripts has global variables that must invoke inside chrome extension, like chrome.storage etc.

I thought so too. Im hoping there could be a work around to improve the development speed.
