### ISSUE TITLE
Choosing between dependencies and devDependencies on package.json

### ISSUE THREAD

**Issue by TimTruston** [ihenvyr/react-chrome-extension#5]
Any good reason why you have react on "dependencies" but redux on "devDependencies" on your package.json? 
Correct me if im wrong - they could work in either places since the production build is done on your local machine anyways... 

Whats included in the production crx file is determined by what you add to the "entry.vendor" tag on webpack.config.prod.js so it doesnt matter whether you included them under "dependencies" or "devDependencies".

**Comment by ihenvyr** [comment]
I forgot what was my reason why, perhaps I just mistakenly add it in dev dependencies. You're correct, it would work either way since we build it locally :)
